// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOo83jIVfhfyLnqHwp-1_7aRgjRTl9dw',
    appId: '1:848916890161:web:f6f495b3dd36d20272cb10',
    messagingSenderId: '848916890161',
    projectId: 'prova-7b84d',
    authDomain: 'prova-7b84d.firebaseapp.com',
    storageBucket: 'prova-7b84d.firebasestorage.app',
    measurementId: 'G-J2KHRNZRQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYc5F06kPxeBE73TCALcB_PsPfdBHEVpI',
    appId: '1:848916890161:android:523a4ff6a76224ff72cb10',
    messagingSenderId: '848916890161',
    projectId: 'prova-7b84d',
    storageBucket: 'prova-7b84d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDga_kYF_crh6hemfAfy54gms_02EzFhEE',
    appId: '1:848916890161:ios:ec0f8f0f9fa7585a72cb10',
    messagingSenderId: '848916890161',
    projectId: 'prova-7b84d',
    storageBucket: 'prova-7b84d.firebasestorage.app',
    iosBundleId: 'com.prova.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDga_kYF_crh6hemfAfy54gms_02EzFhEE',
    appId: '1:848916890161:ios:ec0f8f0f9fa7585a72cb10',
    messagingSenderId: '848916890161',
    projectId: 'prova-7b84d',
    storageBucket: 'prova-7b84d.firebasestorage.app',
    iosBundleId: 'com.prova.app',
  );
}
